parameters:
  workingDirectory: $(system.defaultWorkingDirectory)
  pool:
  idam:
  environments: []
  jobs: []

jobs:
- ${{ each deployment in parameters.environments }}:
  - deployment: Core_Infra_${{ deployment.name }}

    pool:
      name: ${{ parameters.pool }}

    condition: startsWith(variables['Build.SourceBranch'], '${{ deployment.deploymentBranch }}')
    environment: ${{ deployment.name }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true

          - template: terraform-deploy.yml
            parameters:
              workingDirectory: ${{ parameters.workingDirectory }}
              storageAccount: ${{ deployment.storageAccount }}
              environment: ${{ deployment.name }}
              armServiceConnection: ${{ deployment.armServiceConnection }}
              dnsServiceConnection: ${{ deployment.dnsServiceConnection }}
              aksServiceConnection: ${{ deployment.aksServiceConnection }}
              idamTenantId: ${{ parameters.idam.TenantId }}
              idamClientId: ${{ parameters.idam.ClientId }}
              idamClientSecret: ${{ parameters.idam.ClientSecret }}
